name: cron-check
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  tick:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "event: $GITHUB_EVENT_NAME"
          date -u
