name: YUC Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Prepare artifact folders
        run: mkdir -p artifacts

      - name: Run scraper
        run: python yuc/scripts/scrape.py

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: yuc-artifacts
          path: |
            parking_log.csv
            artifacts/
