name: yuc_scrape

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: {}
  push:
    paths:
      - "yuc/**"
      - ".github/workflows/yuc_scrape.yml"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    concurrency:
      group: yuc-scrape
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          # ⚠️ pip 캐시 경로 지정(requirements/pyproject) 없어서 에러 나니 캐시 비활성화

      # ▶ Playwright 브라우저 캐시 (핵심)
      - name: Cache Playwright browsers
        id: pw-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: pw-browsers-${{ runner.os }}-playwright-1.55.0-chromium
          restore-keys: |
            pw-browsers-${{ runner.os }}-playwright-1.55.

      - name: Install Python deps (incl. Playwright)
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install playwright

      # 캐시 미스일 때만 브라우저 다운로드 (절대 --with-deps 쓰지 마)
      - name: Install Playwright browsers (cache miss only)
        if: steps.pw-cache.outputs.cache-hit != 'true'
        run: |
          python -m playwright install chromium

      - name: Run scraper
        env:
          PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright
          PYTHONUNBUFFERED: "1"
          CI: "1"
        run: |
          python yuc/scripts/scrape.py

      - name: Commit & Push CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add yuc/parking_log.csv
          git commit -m "update yuc/parking_log.csv [skip ci]" || echo "no changes"
          git push
